# Generated by Django 5.0.6 on 2024-05-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.TextField(max_length=1000, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='Fecha de registro')),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(null=True, upload_to='products')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.categoria')),
            ],
        ),
    ]
